apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-react-demo-server-db
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kustomize-react-demo-server-db
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: .
    repoURL: {{ .Values.spec.source.backend.repoURL }}
    targetRevision: {{ .Values.spec.source.backend.targetRevision }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
